version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/infrastructure/cdk/'
    reviewers:
      - 'citizensadvice/devops'
      - 'MatthewCane'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/London'
